/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.wordcount;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TopCounts extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1972624842260801374L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TopCounts\",\"namespace\":\"avro.wordcount\",\"fields\":[{\"name\":\"data\",\"type\":{\"type\":\"map\",\"values\":\"long\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TopCounts> ENCODER =
      new BinaryMessageEncoder<TopCounts>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TopCounts> DECODER =
      new BinaryMessageDecoder<TopCounts>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TopCounts> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TopCounts> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TopCounts>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TopCounts to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TopCounts from a ByteBuffer. */
  public static TopCounts fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.Map<java.lang.String,java.lang.Long> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TopCounts() {}

  /**
   * All-args constructor.
   * @param data The new value for data
   */
  public TopCounts(java.util.Map<java.lang.String,java.lang.Long> data) {
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.util.Map<java.lang.String,java.lang.Long>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.util.Map<java.lang.String,java.lang.Long> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.Map<java.lang.String,java.lang.Long> value) {
    this.data = value;
  }

  /**
   * Creates a new TopCounts RecordBuilder.
   * @return A new TopCounts RecordBuilder
   */
  public static avro.wordcount.TopCounts.Builder newBuilder() {
    return new avro.wordcount.TopCounts.Builder();
  }

  /**
   * Creates a new TopCounts RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TopCounts RecordBuilder
   */
  public static avro.wordcount.TopCounts.Builder newBuilder(avro.wordcount.TopCounts.Builder other) {
    return new avro.wordcount.TopCounts.Builder(other);
  }

  /**
   * Creates a new TopCounts RecordBuilder by copying an existing TopCounts instance.
   * @param other The existing instance to copy.
   * @return A new TopCounts RecordBuilder
   */
  public static avro.wordcount.TopCounts.Builder newBuilder(avro.wordcount.TopCounts other) {
    return new avro.wordcount.TopCounts.Builder(other);
  }

  /**
   * RecordBuilder for TopCounts instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TopCounts>
    implements org.apache.avro.data.RecordBuilder<TopCounts> {

    private java.util.Map<java.lang.String,java.lang.Long> data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.wordcount.TopCounts.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TopCounts instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.wordcount.TopCounts other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.Long> getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public avro.wordcount.TopCounts.Builder setData(java.util.Map<java.lang.String,java.lang.Long> value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public avro.wordcount.TopCounts.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TopCounts build() {
      try {
        TopCounts record = new TopCounts();
        record.data = fieldSetFlags()[0] ? this.data : (java.util.Map<java.lang.String,java.lang.Long>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TopCounts>
    WRITER$ = (org.apache.avro.io.DatumWriter<TopCounts>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TopCounts>
    READER$ = (org.apache.avro.io.DatumReader<TopCounts>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
